### ISSUE TITLE
Inject SauceConnect options

### ISSUE THREAD

**Issue by johnroach** [aginteractive/Gradle-Sauce-Connect-Plugin#1]
We need to make SauceConnect option injection available to users of this plugin.

**Comment by zhtaoang** [comment]
It's a hacky way to do it. But before we have this feature ready, we may simply append sauce-connect options to the key of sauceAuth like below:
```
sauceAuth {
   username = "$System.env.SAUCE_USERNAME"
   key = "$System.env.SAUCE_ACCESS_KEY" + " --tunnel-identifier appleTunnel"
}
```
PS: I know you guys already know that. Just FYI for other users. Haha.
PPS: Why not just add one more parameter in sauceAuth to do this, 'options' maybe. It's just a string anyway.

**Comment by johnroach** [comment]
Yup. Will try to do this as soon as I can. However, if you want to feel free to contribute and send a pull request! We would really appreciate it!

**Comment by Josh-a-e** [comment]
Really pleased to see this added, any ideas when it will get released?

**Comment by johnroach** [comment]
Hi @Josh-a-e , this has been merged. Currently waiting for SauceLabs to do a new build. We are thinking of creating a dev release on the gradle plugin site. Please watch this repository for more updates soon!
